apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis
  namespace: tenant-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artemis
  template:
    metadata:
      labels:
        app: artemis
    spec:
      containers:
      - name: artemis
        image: apache-artemis:latest
        ports:
        - containerPort: 61616