apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: tenant-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      initContainers:
        - name: schemagen-init
          image: schemagen-image:latest  
          command: ["/bin/sh", "-c", "echo 'Running schema migration for tenant1...'; sleep 60"] 
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
      containers:
      - name: tomcat
        image: tomcat:latest
        ports:
        - containerPort: 8080