apiVersion: v1
kind: ConfigMap
metadata:
  name: central-config
  namespace: kube-system
data:
  tenants: |
    - name: tenant-1
      nginx_image: "nginx:latest"
      tomcat_image: "tomcat:latest"
      artemis_image: "apache-artemis:latest"
      db_url: "jdbc:postgresql://db/tenant-1"
    - name: tenant-2
      nginx_image: "nginx:latest"
      tomcat_image: "tomcat:latest"
      artemis_image: "apache-artemis:latest"
      db_url: "jdbc:postgresql://db/tenant-2"