apiVersion: v1
kind: ConfigMap
metadata:
  name: maintenance-html
  namespace: tenant-1
data:
  maintenance.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Maintenance</title>
      <style>
        body {
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          background-color: #f2f2f2;
          font-family: Arial, sans-serif;
        }
        .container {
          text-align: center;
        }
        h1 {
          color: #333;
        }
        p {
          color: #666;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>We'll be back soon!</h1>
        <p>We're currently performing scheduled maintenance. Thank you for your patience.</p>
      </div>
    </body>
    </html>
