apiVersion: batch/v1
kind: Job
metadata:
  name: schemagen-job
spec:
  template:
    spec:
      containers:
        - name: schemagen
          image: schemagen-image:latest
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
      restartPolicy: OnFailure
