apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feelgood-app
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-github-account/feelgood-gmbh-saas'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tenant-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true