apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: tenant-1
spec:
  rules:
  - host: tenant-1.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80