apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: tenant-1
type: Opaque
data:
  username: dXNlcm5hbWU= 
  password: cGFzc3dvcmQ=  
  db_url: amRiYzpwb3N0Z3Jlc3FsOi8vZGIvdGVuYW50LTE=  